# Generated by Django 5.2.16 on 2026-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "office_code",
                    models.CharField(
                        choices=[
                            ("GUIDANCE", "Orientamento"),
                            ("ADMIN_OFFICE", "Segreteria studenti"),
                            ("INTERNATIONAL", "Relazioni internazionali"),
                            ("INTERNSHIPS", "Tirocini"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="codice ufficio",
                    ),
                ),
                (
                    "question_it",
                    models.CharField(max_length=255, verbose_name="domanda (italiano)"),
                ),
                (
                    "question_en",
                    models.CharField(max_length=255, verbose_name="domanda (inglese)"),
                ),
                ("answer_it", models.TextField(verbose_name="risposta (italiano)")),
                ("answer_en", models.TextField(verbose_name="risposta (inglese)")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Le FAQ non attive restano in archivio ma non vengono mostrate.",
                        verbose_name="attiva",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creata il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="aggiornata il"),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["office_code", "question_it"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("office_code", "question_it"),
                        name="unique_faq_per_office_and_question",
                    )
                ],
            },
        ),
    ]
