# Generated by Django 5.2.16 on 2026-09-28 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "office_code",
                    models.CharField(
                        choices=[
                            ("GUIDANCE", "Orientamento"),
                            ("ADMIN_OFFICE", "Segreteria studenti"),
                            ("INTERNATIONAL", "Relazioni internazionali"),
                            ("INTERNSHIPS", "Tirocini"),
                        ],
                        help_text="L'ufficio scelto dallo studente, anche se la risposta è di un altro.",
                        max_length=32,
                        verbose_name="codice ufficio",
                    ),
                ),
                ("text", models.TextField(verbose_name="domanda")),
                (
                    "language",
                    models.CharField(
                        choices=[("it", "Italiano"), ("en", "Inglese")],
                        max_length=2,
                        verbose_name="lingua",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="La pertinenza della FAQ proposta; vuoto se non ne è stata trovata una.",
                        null=True,
                        verbose_name="punteggio",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Lo studente ha indicato che la FAQ proposta risponde alla domanda.",
                        verbose_name="risolta",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="posta il"),
                ),
                (
                    "matched_faq",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="faq.faq",
                        verbose_name="FAQ proposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "domanda",
                "verbose_name_plural": "domande",
                "ordering": ["-created_at"],
            },
        ),
    ]
