# Generated by Django 5.2.16 on 2026-10-01 13:18

from django.db import migrations, models


def mark_existing_matches_as_full_text(apps, schema_editor):
    # Until this migration, full-text search was the only way to find a FAQ.
    Inquiry = apps.get_model("faq", "Inquiry")
    Inquiry.objects.filter(score__isnull=False).update(matched_by="fulltext")


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0002_inquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="matched_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fulltext", "ricerca full-text"),
                    ("semantic", "similarità semantica"),
                ],
                help_text="Il metodo che ha trovato la FAQ proposta, e quindi la scala del punteggio.",
                max_length=16,
                verbose_name="trovata con",
            ),
        ),
        migrations.RunPython(
            mark_existing_matches_as_full_text, migrations.RunPython.noop
        ),
    ]
