# Generated by Django 5.2.16 on 2026-10-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0005_remove_faq_office_code_remove_inquiry_office_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="question_en",
            field=models.TextField(verbose_name="domanda (inglese)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_it",
            field=models.TextField(verbose_name="domanda (italiano)"),
        ),
    ]
