# Generated by Django 5.2.16 on 2026-10-06 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0007_inquiry_matched_by"),
        ("offices", "0002_rename_office_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="office",
            field=models.ForeignKey(
                blank=True,
                help_text="L'ufficio scelto dallo studente, anche se la risposta è di un altro. Se non ne ha scelto uno, quello della FAQ proposta; vuoto se non ne è stata trovata una.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inquiries",
                to="offices.office",
                verbose_name="ufficio",
            ),
        ),
    ]
