"""
Django settings for pronto project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


def env_flag(name, default=False):
    """Read a boolean from the environment, where everything is a string.

    Written out rather than `os.getenv(name) == "True"` because DEBUG=true and
    DEBUG=1 are what people actually write in a .env file, and silently reading
    either as False would turn debugging off without saying so.
    """
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# Off unless asked for: a deployment that forgets to set DEBUG gets the safe
# answer, instead of serving tracebacks and settings to whoever triggers a 500.
DEBUG = env_flag("DEBUG")

# Comma-separated, e.g. ALLOWED_HOSTS=pronto.unibo.it,localhost
ALLOWED_HOSTS: list[str] = [
    host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()
]

# Django refuses every request when ALLOWED_HOSTS is empty and DEBUG is off, so
# a local run with neither variable set would answer 400 to everything. In
# debug the default is the developer's own machine, and nothing more.
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "accounts",
    "booking",
    "faq",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = ["http://localhost:5173"]

AUTH_USER_MODEL = "accounts.User"

# These two defaults are load-bearing, not conveniences: LogoutView and MeView
# in accounts/views.py declare no permission_classes of their own and rely on
# IsAuthenticated being the default. Loosening it here silently opens them.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

ROOT_URLCONF = "pronto.urls"

# Email. In development the verification link is printed to the console instead
# of being delivered, so no SMTP account is needed to try the sign-up flow.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@pronto.local")

# Where the verification link sent by email points to.
BACKEND_BASE_URL = os.getenv("BACKEND_BASE_URL", "http://localhost:8000")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pronto.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": {"sslmode": "require"},
    }
}

# Tests run against an in-memory SQLite database: no credentials, no network,
# so the suite is fast locally and works on CI, where .env is not available.
# Development and production keep using the PostgreSQL settings above.
if "PYTEST_VERSION" in os.environ or "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }
    # CI has no .env file, so no SECRET_KEY. Outside tests a missing SECRET_KEY
    # must still be a hard error, so this fallback stays scoped to test runs.
    SECRET_KEY = SECRET_KEY or "django-insecure-key-for-tests-only"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# The helpdesk is in Cesena and its timetable is written in local time: a shift
# declared 9-17 is 9-17 at the office, not 9-17 UTC. Every aware
# datetime the booking grid builds goes through the active timezone, so this
# is what makes a slot mean what the staff and the students think it means.
TIME_ZONE = "Europe/Rome"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
