"""
Django settings for pronto project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlsplit

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


def env_flag(name, default=False):
    """Read a boolean from the environment, where everything is a string.

    Written out rather than `os.getenv(name) == "True"` because DEBUG=true and
    DEBUG=1 are what people actually write in a .env file, and silently reading
    either as False would turn debugging off without saying so.
    """
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# Off unless asked for: a deployment that forgets to set DEBUG gets the safe
# answer, instead of serving tracebacks and settings to whoever triggers a 500.
DEBUG = env_flag("DEBUG")

# Comma-separated, e.g. ALLOWED_HOSTS=pronto.unibo.it,localhost
ALLOWED_HOSTS: list[str] = [
    host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()
]

# Django refuses every request when ALLOWED_HOSTS is empty and DEBUG is off, so
# a local run with neither variable set would answer 400 to everything. In
# debug the default is the developer's own machine, and nothing more.
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "accounts",
    "booking",
    "faq",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = ["http://localhost:5173"]

AUTH_USER_MODEL = "accounts.User"

# These two defaults are load-bearing, not conveniences: LogoutView and MeView
# in accounts/views.py declare no permission_classes of their own and rely on
# IsAuthenticated being the default. Loosening it here silently opens them.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

ROOT_URLCONF = "pronto.urls"

# Email. In development the verification link is printed to the console instead
# of being delivered, so no SMTP account is needed to try the sign-up flow.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@pronto.local")
# SMTP, read only when EMAIL_BACKEND is set to
# django.core.mail.backends.smtp.EmailBackend. Booking e-mails are sent after
# the booking commits, so a slow server delays the response but never a
# database transaction; the timeout keeps that delay bounded.
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_flag("EMAIL_USE_TLS", default=True)
EMAIL_TIMEOUT = 10

# Where the verification link sent by email points to.
BACKEND_BASE_URL = os.getenv("BACKEND_BASE_URL", "http://localhost:8000")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pronto.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        # The hosted database only accepts encrypted connections, hence the
        # default. The PostgreSQL in docker-compose.yml has no certificate and
        # sets DB_SSLMODE=disable.
        "OPTIONS": {"sslmode": os.getenv("DB_SSLMODE", "require")},
    }
}


def postgres_from_url(url):
    """Django database settings for a postgres://user:password@host:port/name URL.

    One variable rather than a TEST_DB_* copy of every DB_* key, so a test run
    never picks up the development credentials from .env by accident. The
    query string may carry `sslmode`; without it libpq tries SSL and falls back
    to a plain connection, which suits both a local container and CI.
    """
    parts = urlsplit(url)
    if parts.scheme not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured(
            f"TEST_DATABASE_URL must be a postgres:// URL, not {parts.scheme}://"
        )
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(parts.path.lstrip("/")),
        "USER": unquote(parts.username or ""),
        "PASSWORD": unquote(parts.password or ""),
        "HOST": parts.hostname or "",
        "PORT": str(parts.port or 5432),
        "OPTIONS": {"sslmode": parse_qs(parts.query).get("sslmode", ["prefer"])[0]},
    }


# Tests run against an in-memory SQLite database by default: no credentials, no
# network, so the suite is fast and needs nothing but Python. SQLite is not
# PostgreSQL, though — no full-text search, no real row locking — so setting
# TEST_DATABASE_URL runs the same suite against a PostgreSQL server instead,
# as CI does. Django creates and drops its own test_<name> database there.
# Development and production keep using the DB_* settings above.
if "PYTEST_VERSION" in os.environ or "test" in sys.argv:
    test_database_url = os.getenv("TEST_DATABASE_URL")
    if test_database_url:
        DATABASES["default"] = postgres_from_url(test_database_url)
    else:
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    # CI has no .env file, so no SECRET_KEY. Outside tests a missing SECRET_KEY
    # must still be a hard error, so this fallback stays scoped to test runs.
    SECRET_KEY = SECRET_KEY or "django-insecure-key-for-tests-only"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# The helpdesk is in Cesena and its timetable is written in local time: a shift
# declared 9-17 is 9-17 at the office, not 9-17 UTC. Every aware
# datetime the booking grid builds goes through the active timezone, so this
# is what makes a slot mean what the staff and the students think it means.
TIME_ZONE = "Europe/Rome"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# FAQ matching (faq/matching.py)
# The lowest full-text rank at which a FAQ is suggested as the answer to a
# question. A word of the question found in a FAQ's question counts about 0.6,
# one found only in its answer about 0.25, and the rank is the average over the
# meaningful words of the question. Calibrated on the 178 real FAQs with 21
# rephrased questions and 10 that no FAQ answers: below 0.45, wrong answers
# score as high as right ones (a single shared word such as "ora" or "campus"
# reaches 0.2-0.3), and at 0.1 every one of the 10 got a FAQ. What full text
# lets through is left to semantic search (FAQ_SEMANTIC_MIN_SIMILARITY below).
FAQ_MATCH_MIN_RANK = 0.45


# Semantic FAQ matching (faq/vector_index.py)
# Chroma holds the embeddings of the published FAQs and is asked only when
# full-text search finds nothing (see faq/matching.py). With CHROMA_HOST empty,
# semantic matching is off and full-text search works alone; docker-compose.yml
# points it at its chroma service. Tests never reach a server: the ones about
# semantic matching give it an in-memory store of their own.
CHROMA_HOST = os.getenv("CHROMA_HOST", "")
CHROMA_PORT = int(os.getenv("CHROMA_PORT", "8000"))
if "PYTEST_VERSION" in os.environ or "test" in sys.argv:
    CHROMA_HOST = ""
# Multilingual, so Italian and English questions are embedded equally well. It
# runs on ONNX through fastembed, without PyTorch, and is downloaded on first
# use (about 220 MB).
FAQ_EMBEDDING_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
# The lowest cosine similarity, between the question and a FAQ's question, at
# which a FAQ is suggested; its scale has nothing to do with FAQ_MATCH_MIN_RANK.
# Same calibration as above: rephrased questions find their FAQ at 0.70-1.00,
# Italian and English alike, while the closest FAQ to a question none answers
# scores 0.37-0.65 ("A che ora apre la mensa?" -> an open day, 0.65). Together
# with full text at 0.45: 14 of 21 answered right, 2 wrong, none of the 10
# answered. Inquiry.matched_by and resolved are there to check this on real
# questions.
FAQ_SEMANTIC_MIN_SIMILARITY = 0.7
