# Generated by Django 5.2.16 on 2026-09-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "utente", "verbose_name_plural": "utenti"},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Indirizzo istituzionale, usato anche come credenziale di accesso.",
                max_length=254,
                unique=True,
                verbose_name="indirizzo email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Diventa vero quando l'utente apre il link di verifica ricevuto per email.",
                verbose_name="attivo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Studente"),
                    ("EMPLOYEE", "Dipendente"),
                    ("ADMIN", "Amministratore"),
                ],
                help_text="Derivato dal dominio dell'indirizzo email in fase di registrazione.",
                max_length=16,
                verbose_name="ruolo",
            ),
        ),
    ]
