# Generated by Django 5.2.16 on 2026-09-28 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options_alter_user_email_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="degree_programme",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Solo per gli studenti: il corso di laurea a cui sono iscritti.",
                max_length=200,
                verbose_name="corso di studi",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="matricola",
            field=models.CharField(
                blank=True,
                default="",
                error_messages={
                    "unique": "A student with this matricola is already registered."
                },
                help_text="Solo per gli studenti: il numero di matricola Unibo, da 6 a 10 cifre.",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{6,10}$", "A matricola is a number of 6 to 10 digits."
                    )
                ],
                verbose_name="matricola",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("matricola", ""), _negated=True),
                fields=("matricola",),
                name="unique_matricola",
                violation_error_message="A student with this matricola is already registered.",
            ),
        ),
    ]
