# Generated by Django 5.2.16 on 2026-10-01 13:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_matricola_degree_programme"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utente",
                    ),
                ),
                (
                    "matricola",
                    models.CharField(
                        error_messages={
                            "unique": "A student with this matricola is already registered."
                        },
                        help_text="Il numero di matricola Unibo, da 6 a 10 cifre.",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{6,10}$",
                                "A matricola is a number of 6 to 10 digits.",
                            )
                        ],
                        verbose_name="matricola",
                    ),
                ),
                (
                    "degree_programme",
                    models.CharField(
                        help_text="Il corso di laurea a cui lo studente è iscritto.",
                        max_length=200,
                        verbose_name="corso di studi",
                    ),
                ),
            ],
            options={
                "verbose_name": "profilo studente",
                "verbose_name_plural": "profili studenti",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("matricola", ""), _negated=True),
                        name="student_profile_matricola_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("degree_programme", ""), _negated=True),
                        name="student_profile_degree_programme_not_empty",
                    ),
                ],
            },
        ),
    ]
