# Generated by Django 5.2.16 on 2026-10-01 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_copy_student_data"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_matricola",
        ),
        migrations.RemoveField(
            model_name="user",
            name="degree_programme",
        ),
        migrations.RemoveField(
            model_name="user",
            name="matricola",
        ),
    ]
