# Generated by Django 5.2.16 on 2026-10-01 13:51
#
# Every user needs a first and a last name, admins included, and the database
# refuses an empty one. Users without them stop the migration first, with a
# list of who they are: names cannot be made up, and the constraint's own
# error would not say whom it is about.

from django.db import migrations, models
from django.db.models import Q


def check_names(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    unnamed = User.objects.filter(Q(first_name="") | Q(last_name="")).order_by("pk")
    if unnamed.exists():
        emails = ", ".join(unnamed.values_list("email", flat=True))
        raise RuntimeError(
            f"These users have no first or last name: {emails}. Give them one, "
            "then migrate again."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_user_matricola_degree_programme"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(check_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("first_name", ""), _negated=True),
                name="user_first_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_name", ""), _negated=True),
                name="user_last_name_not_empty",
            ),
        ),
    ]
