# Generated by Django 5.2.16 on 2026-10-06 15:55
"""Accounts are active from registration on: e-mail verification is gone.

New users get ``is_active=True`` by default. The users who registered while
verification existed and never opened their link are still inactive, and with
the link gone nothing would ever activate them: this migration does.

Which rows: inactive users who have never logged in (``last_login IS NULL``).
An account could only log in once verified, so an inactive one with a login
was deactivated afterwards, by an admin, and stays inactive. The trade-off: an
account an admin deactivated before it ever logged in looks exactly like an
unverified one, and is activated too. So is one that only logged in before
token logins were recorded, and was deactivated later: the login endpoint has
set ``last_login`` since 1 October 2026, and left it NULL before. Nothing in
the table tells these apart. When this migration was written, the inactive users on the hosted database
were all unverified registrations; an admin who has deactivated someone since
should check the user list in the admin after migrating.

Going back changes no data. Which users this migration activated is not
recorded, and deactivating every user who has never logged in would also lock
out those registered, active, after it ran. Reverting the code restores
verification for new registrations only.

The schema change is the default and the help text alone: Django keeps field
defaults in Python, so the ``AlterField`` runs no SQL.
"""

from django.db import migrations, models


def activate_unverified(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_active=False, last_login__isnull=True).update(is_active=True)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_require_user_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Toglilo per impedire all'utente di accedere, invece di "
                    "eliminarne l'account."
                ),
                verbose_name="attivo",
            ),
        ),
        migrations.RunPython(activate_unverified, migrations.RunPython.noop),
    ]
