# Generated by Django 5.2.16 on 2026-09-10 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("GUIDANCE", "Orientamento"),
                            ("ADMIN_OFFICE", "Segreteria studenti"),
                            ("INTERNATIONAL", "Relazioni internazionali"),
                            ("INTERNSHIPS", "Tirocini"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="codice ufficio",
                    ),
                ),
                (
                    "name_it",
                    models.CharField(max_length=128, verbose_name="nome (italiano)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=128, verbose_name="nome (inglese)"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="email di contatto"),
                ),
                (
                    "slot_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Lunghezza di un appuntamento presso questo ufficio.",
                        verbose_name="durata dello slot (minuti)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Gli uffici non attivi non accettano nuove prenotazioni.",
                        verbose_name="attivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "ufficio",
                "verbose_name_plural": "uffici",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utente",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="booking.office",
                        verbose_name="ufficio",
                    ),
                ),
            ],
            options={
                "verbose_name": "profilo dipendente",
                "verbose_name_plural": "profili dipendenti",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.DateTimeField(verbose_name="inizio dell'appuntamento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Prenotato"),
                            ("CANCELLED", "Annullato"),
                            ("COMPLETED", "Completato"),
                        ],
                        default="BOOKED",
                        max_length=16,
                        verbose_name="stato",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="La domanda scritta dallo studente, mostrata al dipendente.",
                        verbose_name="domanda",
                    ),
                ),
                (
                    "question_lang",
                    models.CharField(
                        choices=[("it", "Italiano"), ("en", "Inglese")],
                        max_length=2,
                        verbose_name="lingua della domanda",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="aggiornato il"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="studente",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="booking.employeeprofile",
                        verbose_name="dipendente",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="booking.office",
                        verbose_name="ufficio",
                    ),
                ),
            ],
            options={
                "verbose_name": "appuntamento",
                "verbose_name_plural": "appuntamenti",
                "ordering": ["-slot"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "BOOKED")),
                        fields=("employee", "slot"),
                        name="unique_booked_slot_per_employee",
                    )
                ],
            },
        ),
    ]
