# Generated by Django 5.2.16 on 2026-09-24 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "lunedì"),
                            (1, "martedì"),
                            (2, "mercoledì"),
                            (3, "giovedì"),
                            (4, "venerdì"),
                            (5, "sabato"),
                            (6, "domenica"),
                        ],
                        verbose_name="giorno della settimana",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="inizio")),
                ("end_time", models.TimeField(verbose_name="fine")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="booking.employeeprofile",
                        verbose_name="dipendente",
                    ),
                ),
            ],
            options={
                "verbose_name": "turno",
                "verbose_name_plural": "turni",
                "ordering": ["weekday", "start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_time__lt", models.F("end_time"))),
                        name="shift_ends_after_it_starts",
                    )
                ],
            },
        ),
    ]
