# Generated by Django 5.2.16 on 2026-09-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_shift"),
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="suggested_faq",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="faq.faq",
                verbose_name="FAQ proposta",
            ),
        ),
    ]
